# Python stubs generated by omniidl from SimpleService.idl

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA

_omnipy.checkVersion(3,0, __file__)


#
# Start of module "ysuga"
#
__name__ = "ysuga"
_0_ysuga = omniORB.openModule("ysuga", r"SimpleService.idl")
_0_ysuga__POA = omniORB.openModule("ysuga__POA", r"SimpleService.idl")


# interface SimpleService
_0_ysuga._d_SimpleService = (omniORB.tcInternal.tv_objref, "IDL:ysuga/SimpleService:1.0", "SimpleService")
omniORB.typeMapping["IDL:ysuga/SimpleService:1.0"] = _0_ysuga._d_SimpleService
_0_ysuga.SimpleService = omniORB.newEmptyClass()
class SimpleService :
    _NP_RepositoryId = _0_ysuga._d_SimpleService[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_ysuga.SimpleService = SimpleService
_0_ysuga._tc_SimpleService = omniORB.tcInternal.createTypeCode(_0_ysuga._d_SimpleService)
omniORB.registerType(SimpleService._NP_RepositoryId, _0_ysuga._d_SimpleService, _0_ysuga._tc_SimpleService)

# SimpleService operations and attributes
SimpleService._d_read = ((), (omniORB.tcInternal.tv_long, omniORB.tcInternal.tv_long), None)
SimpleService._d_write = ((omniORB.tcInternal.tv_long, ), (omniORB.tcInternal.tv_long, ), None)
SimpleService._d_reset = ((), (omniORB.tcInternal.tv_long, ), None)

# SimpleService object reference
class _objref_SimpleService (CORBA.Object):
    _NP_RepositoryId = SimpleService._NP_RepositoryId

    def __init__(self):
        CORBA.Object.__init__(self)

    def read(self, *args):
        return _omnipy.invoke(self, "read", _0_ysuga.SimpleService._d_read, args)

    def write(self, *args):
        return _omnipy.invoke(self, "write", _0_ysuga.SimpleService._d_write, args)

    def reset(self, *args):
        return _omnipy.invoke(self, "reset", _0_ysuga.SimpleService._d_reset, args)

    __methods__ = ["read", "write", "reset"] + CORBA.Object.__methods__

omniORB.registerObjref(SimpleService._NP_RepositoryId, _objref_SimpleService)
_0_ysuga._objref_SimpleService = _objref_SimpleService
del SimpleService, _objref_SimpleService

# SimpleService skeleton
__name__ = "ysuga__POA"
class SimpleService (PortableServer.Servant):
    _NP_RepositoryId = _0_ysuga.SimpleService._NP_RepositoryId


    _omni_op_d = {"read": _0_ysuga.SimpleService._d_read, "write": _0_ysuga.SimpleService._d_write, "reset": _0_ysuga.SimpleService._d_reset}

SimpleService._omni_skeleton = SimpleService
_0_ysuga__POA.SimpleService = SimpleService
omniORB.registerSkeleton(SimpleService._NP_RepositoryId, SimpleService)
del SimpleService
__name__ = "ysuga"

#
# End of module "ysuga"
#
__name__ = "SimpleService_idl"

_exported_modules = ( "ysuga", )

# The end.
